#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"
STATE_DIR="$ROOT_DIR/.app_state"
STATE_FILE="$STATE_DIR/engine-selection.env"

mkdir -p "$STATE_DIR/media/workspaces" "$STATE_DIR/media/uploads"

OS_NAME="$(uname -s)"
ARCH_NAME="$(uname -m)"
HOST_GMX="$(command -v gmx || true)"
ENGINE="docker-cpu"
COMPOSE_PROFILES="cpu"
EXECUTION_MODE="docker-cpu"
GROMACS_BINARY=""
NOTES="CPU Docker engine selected."

if [[ "$OS_NAME" == "Darwin" && "$ARCH_NAME" == "arm64" ]]; then
  if [[ -n "$HOST_GMX" ]] && "$HOST_GMX" --version 2>/dev/null | grep -qi "GPU support:.*OpenCL"; then
    ENGINE="mac-opencl-native"
    COMPOSE_PROFILES=""
    EXECUTION_MODE="native-opencl"
    GROMACS_BINARY="$HOST_GMX"
    NOTES="Apple Silicon detected with native GROMACS OpenCL support. GROWebby will run the backend on macOS so GROMACS can use the M-series GPU."
  else
    ENGINE="docker-backend-cpu"
    COMPOSE_PROFILES=""
    EXECUTION_MODE="backend-gmx-2026.2"
    GROMACS_BINARY="/usr/local/gromacs/bin/gmx"
    NOTES="Apple Silicon detected, but no native OpenCL-enabled gmx was found. GROWebby will run GROMACS 2026.2 inside Docker with CPU/OpenMP support. Install a native OpenCL GROMACS build to enable the M-series GPU path."
  fi
elif command -v nvidia-smi >/dev/null 2>&1; then
  ENGINE="linux-nvidia-cuda"
  COMPOSE_PROFILES="cuda"
  EXECUTION_MODE="docker-cuda"
  NOTES="NVIDIA GPU detected. CUDA Docker engine profile selected."
elif [[ "$OS_NAME" == "Linux" ]]; then
  ENGINE="linux-cpu"
  COMPOSE_PROFILES="cpu"
  EXECUTION_MODE="docker-cpu"
  NOTES="Linux host without NVIDIA GPU detection. CPU Docker engine profile selected."
fi

cat > "$ENV_FILE" <<EOF
# Generated by install.sh. Edit only if you want to override auto-detection.
GROWEBBY_ENGINE=$ENGINE
COMPOSE_PROFILES=$COMPOSE_PROFILES
GROMACS_EXECUTION_MODE=$EXECUTION_MODE
GROMACS_BINARY=$GROMACS_BINARY
GROMACS_WORK_ROOT=/app/media/workspaces
GROWEBBY_MEDIA_ROOT=$STATE_DIR/media
EOF

cat > "$STATE_FILE" <<EOF
GROWEBBY_ENGINE=$ENGINE
COMPOSE_PROFILES=$COMPOSE_PROFILES
GROMACS_EXECUTION_MODE=$EXECUTION_MODE
GROMACS_BINARY=$GROMACS_BINARY
GROMACS_WORK_ROOT=/app/media/workspaces
GROWEBBY_MEDIA_ROOT=$STATE_DIR/media
NOTES="$NOTES"
EOF

echo "GROWebby engine selection"
echo "  Host: $OS_NAME $ARCH_NAME"
echo "  Engine: $ENGINE"
echo "  Compose profiles: ${COMPOSE_PROFILES:-none}"
echo "  Execution mode: $EXECUTION_MODE"
if [[ "$ENGINE" == "mac-opencl-native" ]]; then
  echo "  Native gmx: $GROMACS_BINARY"
elif [[ "$ENGINE" == "docker-backend-cpu" ]]; then
  echo "  Container gmx: $GROMACS_BINARY"
elif [[ -n "$GROMACS_BINARY" ]]; then
  echo "  Native gmx: $GROMACS_BINARY"
fi
echo "  Notes: $NOTES"
echo
echo "Wrote $ENV_FILE"
