#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"
STATE_DIR="$ROOT_DIR/.app_state"
STATE_FILE="$STATE_DIR/engine-selection.env"

mkdir -p "$STATE_DIR"

OS_NAME="$(uname -s)"
ARCH_NAME="$(uname -m)"
ENGINE="docker-cpu"
COMPOSE_PROFILES="cpu"
EXECUTION_MODE="docker-cpu"
GROMACS_BINARY=""
NOTES="CPU Docker engine selected."

if [[ "$OS_NAME" == "Darwin" && "$ARCH_NAME" == "arm64" ]]; then
  ENGINE="mac-opencl-native"
  COMPOSE_PROFILES=""
  EXECUTION_MODE="native-opencl"
  GROMACS_BINARY="$(command -v gmx || true)"
  NOTES="Apple Silicon detected. CUDA is unavailable on this platform. Use a native GROMACS OpenCL build for Mac GPU execution; Docker services will run the web app."
elif command -v nvidia-smi >/dev/null 2>&1; then
  ENGINE="linux-nvidia-cuda"
  COMPOSE_PROFILES="cuda"
  EXECUTION_MODE="docker-cuda"
  NOTES="NVIDIA GPU detected. CUDA Docker engine profile selected."
elif [[ "$OS_NAME" == "Linux" ]]; then
  ENGINE="linux-cpu"
  COMPOSE_PROFILES="cpu"
  EXECUTION_MODE="docker-cpu"
  NOTES="Linux host without NVIDIA GPU detection. CPU Docker engine profile selected."
fi

cat > "$ENV_FILE" <<EOF
# Generated by install.sh. Edit only if you want to override auto-detection.
GROWEBBY_ENGINE=$ENGINE
COMPOSE_PROFILES=$COMPOSE_PROFILES
GROMACS_EXECUTION_MODE=$EXECUTION_MODE
GROMACS_BINARY=$GROMACS_BINARY
EOF

cat > "$STATE_FILE" <<EOF
GROWEBBY_ENGINE=$ENGINE
COMPOSE_PROFILES=$COMPOSE_PROFILES
GROMACS_EXECUTION_MODE=$EXECUTION_MODE
GROMACS_BINARY=$GROMACS_BINARY
NOTES="$NOTES"
EOF

echo "GROWebby engine selection"
echo "  Host: $OS_NAME $ARCH_NAME"
echo "  Engine: $ENGINE"
echo "  Compose profiles: ${COMPOSE_PROFILES:-none}"
echo "  Execution mode: $EXECUTION_MODE"
if [[ -n "$GROMACS_BINARY" ]]; then
  echo "  Native gmx: $GROMACS_BINARY"
elif [[ "$ENGINE" == "mac-opencl-native" ]]; then
  echo "  Native gmx: not found"
  echo "  Install a native GROMACS OpenCL build before expecting Mac GPU execution."
fi
echo "  Notes: $NOTES"
echo
echo "Wrote $ENV_FILE"
