#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"
STATE_DIR="$ROOT_DIR/.app_state"
STATE_FILE="$STATE_DIR/engine-selection.env"

mkdir -p "$STATE_DIR/media/workspaces" "$STATE_DIR/media/uploads"

OS_NAME="$(uname -s)"
ARCH_NAME="$(uname -m)"
HOST_GMX="$(command -v gmx || true)"
REPO="ramsainanduri"
ENGINE="linux-cpu"
COMPOSE_PROFILES="cpu"
EXECUTION_MODE="backend-gmx-2026.2"
GROMACS_BINARY="/usr/local/gromacs/bin/gmx"
BACKEND_BASE_IMAGE="${REPO}/growebby-base-backend-cpu:latest"
STATUS="CPU Docker engine profile selected."

if [[ "$OS_NAME" == "Darwin" && "$ARCH_NAME" == "arm64" ]]; then
  if [[ -n "$HOST_GMX" ]] && "$HOST_GMX" --version 2>/dev/null | grep -qi "GPU support:.*OpenCL"; then
    ENGINE="mac-opencl-native"
    COMPOSE_PROFILES=""
    EXECUTION_MODE="native-opencl"
    GROMACS_BINARY="$HOST_GMX"
    BACKEND_BASE_IMAGE="${REPO}/growebby-base-backend-metal:latest"
    STATUS="Apple Silicon with native GROMACS OpenCL. Backend runs on macOS, GPU via M-series."
  else
    ENGINE="linux-cpu"
    COMPOSE_PROFILES=""
    EXECUTION_MODE="backend-gmx-2026.2"
    GROMACS_BINARY="/usr/local/gromacs/bin/gmx"
    BACKEND_BASE_IMAGE="${REPO}/growebby-base-backend-cpu:latest"
    STATUS="Apple Silicon without native OpenCL gmx. Running GROMACS 2026.2 in Docker with CPU/OpenMP."
  fi
elif command -v nvidia-smi >/dev/null 2>&1; then
  ENGINE="linux-nvidia-cuda"
  COMPOSE_PROFILES="cuda"
  EXECUTION_MODE="backend-gmx-2026.2"
  GROMACS_BINARY="/usr/local/gromacs/bin/gmx"
  BACKEND_BASE_IMAGE="${REPO}/growebby-base-backend-cuda:latest"
  STATUS="NVIDIA GPU detected. CUDA Docker engine profile selected."
elif [[ "$OS_NAME" == "Linux" ]]; then
  ENGINE="linux-cpu"
  COMPOSE_PROFILES="cpu"
  EXECUTION_MODE="backend-gmx-2026.2"
  GROMACS_BINARY="/usr/local/gromacs/bin/gmx"
  BACKEND_BASE_IMAGE="${REPO}/growebby-base-backend-cpu:latest"
  STATUS="Linux without NVIDIA GPU. CPU Docker engine profile selected."
fi

cat > "$ENV_FILE" <<EOF
# Generated by install.sh. Edit only if you want to override auto-detection.
GROWEBBY_ENGINE=$ENGINE
COMPOSE_PROFILES=$COMPOSE_PROFILES
GROMACS_EXECUTION_MODE=$EXECUTION_MODE
GROMACS_BINARY=$GROMACS_BINARY
GROMACS_WORK_ROOT=/app/media/workspaces
GROWEBBY_MEDIA_ROOT=$STATE_DIR/media
BACKEND_BASE_IMAGE=$BACKEND_BASE_IMAGE
EOF

cat > "$STATE_FILE" <<EOF
GROWEBBY_ENGINE=$ENGINE
COMPOSE_PROFILES=$COMPOSE_PROFILES
GROMACS_EXECUTION_MODE=$EXECUTION_MODE
GROMACS_BINARY=$GROMACS_BINARY
GROMACS_WORK_ROOT=/app/media/workspaces
GROWEBBY_MEDIA_ROOT=$STATE_DIR/media
STATUS="$STATUS"
EOF

echo "GROWebby engine selection"
echo "  Host: $OS_NAME $ARCH_NAME"
echo "  Engine: $ENGINE"
echo "  Compose profiles: ${COMPOSE_PROFILES:-none}"
echo "  Execution mode: $EXECUTION_MODE"
if [[ "$ENGINE" == "mac-opencl-native" ]]; then
  echo "  Native gmx: $GROMACS_BINARY"
elif [[ "$ENGINE" == "docker-backend-cpu" ]]; then
  echo "  Container gmx: $GROMACS_BINARY"
elif [[ -n "$GROMACS_BINARY" ]]; then
  echo "  Native gmx: $GROMACS_BINARY"
fi
echo "  Status: $STATUS"
echo
echo "Wrote $ENV_FILE"
