# Generated by Django 6.0.6 on 2026-06-15 02:08

import simulations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0004_simulationjob_process_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcoordinate',
            name='file',
            field=models.FileField(upload_to=simulations.models.user_upload_path),
        ),
    ]
